import Evm.Operations


import Evm.State
import Evm.Exception
import Evm.Semantics.PrimOps
import Evm.StateOps
import Evm.Wheels

import Evm.UInt256
import Evm.StateOps
import Evm.Machine.SharedStateOps
import Evm.Machine.MachineStateOps

import Evm.Crypto.Keccak256

--

import Mathlib.Data.BitVec
import Mathlib.Data.Array.Defs
import Mathlib.Data.Finmap
import Mathlib.Data.List.Defs
import Evm.Machine.Stack

import Evm.Maps.AccountMap
import Evm.Maps.AccountMap

import Evm.State.AccountOps
import Evm.State.ExecutionEnv
import Evm.State.Substate
import Evm.State.TransactionOps

import Evm.Exception
import Evm.Semantics.Gas
import Evm.Semantics.GasConstants
import Evm.State
import Evm.StateOps
import Evm.Exception
import Evm.Instr
import Evm.Semantics.Precompiles

import Evm.Operations
import Evm.Pretty
import Evm.Machine.SharedStateOps
import Evm.Wheels
import Evm.Crypto.EllipticCurves
import Evm.UInt256
import Evm.Machine.MachineState

--

namespace Evm

section Semantics

open Stack

def dup (n : ℕ) : Transformer :=
  λ s ↦
  match s.stack[n-1]? with
    | some v => .ok <| s.replaceStackAndIncrPC (v :: s.stack)
    | none => .error .StackUnderflow

def swap (n : ℕ) : Transformer :=
  λ s ↦
  let top := s.stack.take (n + 1)
  let bottom := s.stack.drop (n + 1)
  if List.length top = (n + 1) then
    .ok <| s.replaceStackAndIncrPC (top.getLast! :: top.tail!.dropLast ++ [top.head!] ++ bottom)
  else
    .error .StackUnderflow

def stepPrimop (op : Operation) (arg : Option (UInt256 × Nat) := .none) : Transformer :=
  match op with
    -- TODO: Revisit STOP, this is likely not the best way to do it.
    | .STOP =>
      λ evmState ↦ .ok <| {evmState with toMachineState := evmState.toMachineState.setReturnData .empty}
    | .ADD =>
      execBinOp UInt256.add
    | .MUL =>
      execBinOp UInt256.mul
    | .SUB =>
      execBinOp UInt256.sub
    | .DIV =>
      execBinOp UInt256.div
    | .SDIV =>
      execBinOp UInt256.sdiv
    | .MOD =>
      execBinOp UInt256.mod
    | .SMOD =>
      execBinOp UInt256.smod
    | .ADDMOD =>
      execTriOp UInt256.addMod
    | .MULMOD =>
      execTriOp UInt256.mulMod
    | .EXP =>
      execBinOp UInt256.exp
    | .SIGNEXTEND =>
      execBinOp UInt256.signextend
    | .LT =>
      execBinOp UInt256.lt
    | .GT =>
      execBinOp UInt256.gt
    | .SLT =>
      execBinOp UInt256.slt
    | .SGT =>
      execBinOp UInt256.sgt
    | .EQ =>
      execBinOp UInt256.eq
    | .ISZERO =>
      execUnOp UInt256.isZero
    | .AND =>
      execBinOp UInt256.land
    | .OR =>
      execBinOp UInt256.lor
    | .XOR =>
      execBinOp UInt256.xor
    | .NOT =>
      execUnOp UInt256.lnot
    | .BYTE =>
      execBinOp UInt256.byteAt
    | .SHL =>
      execBinOp (flip UInt256.shiftLeft)
    | .SHR =>
      execBinOp (flip UInt256.shiftRight)
    | .SAR =>
      execBinOp UInt256.sar

    | .KECCAK256 =>
      binaryMachineStateOp' MachineState.keccak256

    | .ADDRESS =>
      executionEnvOp (.ofNat ∘ Fin.val ∘ ExecutionEnv.codeOwner)
    | .BALANCE =>
      unaryStateOp Evm.State.balance
    | .ORIGIN =>
      executionEnvOp (.ofNat ∘ Fin.val ∘ ExecutionEnv.sender)
    | .CALLER =>
      executionEnvOp (.ofNat ∘ Fin.val ∘ ExecutionEnv.source)
    | .CALLVALUE =>
      executionEnvOp ExecutionEnv.weiValue
    | .CALLDATALOAD =>
      unaryStateOp (λ s v ↦ (s, Evm.State.calldataload s v))
    | .CALLDATASIZE =>
      executionEnvOp (.ofNat ∘ ByteArray.size ∘ ExecutionEnv.calldata)
    | .CALLDATACOPY =>
      ternaryCopyOp .calldatacopy
    | .CODESIZE =>
      executionEnvOp (.ofNat ∘ ByteArray.size ∘ ExecutionEnv.code)
    | .CODECOPY =>
      ternaryCopyOp .codeCopy
    | .GASPRICE =>
      executionEnvOp (.ofNat ∘ ExecutionEnv.gasPrice)
    | .EXTCODESIZE =>
      unaryStateOp Evm.State.extCodeSize
    | .EXTCODECOPY =>
      quaternaryCopyOp Evm.SharedState.extCodeCopy'
    | .RETURNDATASIZE =>
      machineStateOp Evm.MachineState.returndatasize
    | .RETURNDATACOPY =>
            λ evmState ↦
        match evmState.stack.pop3 with
          | some ⟨stack', μ₀, μ₁, μ₂⟩ => do
            let mState' := evmState.toMachineState.returndatacopy μ₀ μ₁ μ₂
            let evmState' := {evmState with toMachineState := mState'}
            .ok <| evmState'.replaceStackAndIncrPC stack'
          | _ => .error .StackUnderflow
    | .EXTCODEHASH => unaryStateOp Evm.State.extCodeHash

    | .BLOCKHASH => unaryStateOp (λ s v ↦ (s, Evm.State.blockHash s v))
    | .COINBASE => stateOp (.ofNat ∘ Fin.val ∘ Evm.State.coinBase)
    | .TIMESTAMP =>
      stateOp Evm.State.timeStamp
    | .NUMBER => stateOp Evm.State.number
    -- "RANDAO is a pseudorandom value generated by validators on the Ethereum consensus layer"
    -- "the details of generating the RANDAO value on the Beacon Chain is beyond the scope of this paper"
    | .PREVRANDAO => executionEnvOp Evm.prevRandao
    | .GASLIMIT => stateOp Evm.State.gasLimit
    | .CHAINID => stateOp Evm.State.chainId
    | .SELFBALANCE => stateOp Evm.State.selfbalance
    | .BASEFEE => executionEnvOp Evm.basefee
    | .BLOBHASH => unaryExecutionEnvOp blobhash
    | .BLOBBASEFEE => executionEnvOp Evm.ExecutionEnv.getBlobGasprice

    | .POP =>
      λ evmState ↦
      match evmState.stack.pop with
        | some ⟨ s , _ ⟩ => .ok <| evmState.replaceStackAndIncrPC s
        | _ => .error .StackUnderflow

    | .MLOAD => λ evmState ↦
      match evmState.stack.pop with
        | some ⟨ s , μ₀ ⟩ => Id.run do
          let (v, mState') := evmState.toMachineState.mload μ₀
          let evmState' := {evmState with toMachineState := mState'}
          .ok <| evmState'.replaceStackAndIncrPC (s.push v)
        | _ => .error .StackUnderflow
    | .MSTORE =>
      binaryMachineStateOp MachineState.mstore
    | .MSTORE8 => binaryMachineStateOp MachineState.mstore8
    | .SLOAD =>
      unaryStateOp Evm.State.sload
    | .SSTORE =>
      binaryStateOp Evm.State.sstore
    | .TLOAD => unaryStateOp Evm.State.tload
    | .TSTORE => binaryStateOp Evm.State.tstore
    | .MSIZE => machineStateOp MachineState.msize
    | .GAS =>
      machineStateOp MachineState.gas
    | .MCOPY => ternaryMachineStateOp MachineState.mcopy

    | .LOG0 => log0Op
    | .LOG1 => log1Op
    | .LOG2 => log2Op
    | .LOG3 => log3Op
    | .LOG4 => log4Op
    | .RETURN => binaryMachineStateOp MachineState.evmReturn
    | .REVERT => binaryMachineStateOp MachineState.evmRevert
    | .SELFDESTRUCT =>
      λ evmState ↦
        match evmState.stack.pop with
          | some ⟨ s , μ₁ ⟩ =>
            let Iₐ := evmState.executionEnv.codeOwner
            let r : AccountAddress := AccountAddress.ofUInt256 μ₁
            if evmState.createdAccounts.contains Iₐ then
              -- When `SELFDESTRUCT` is executed in the same transaction as the contract was created
              let A' : Substate :=
                { evmState.substate with
                    selfDestructSet :=
                      evmState.substate.selfDestructSet.insert Iₐ
                    accessedAccounts :=
                      evmState.substate.accessedAccounts.insert r
                }
              let accountMap' :=
                match evmState.lookupAccount Iₐ with
                  | none =>
                    dbg_trace "No 'self' found to be destructed; this should probably not be happening;"; evmState.accountMap
                  | some σ_Iₐ  =>
                    match evmState.lookupAccount r with
                      | none =>
                        if σ_Iₐ.balance == 0 then
                          evmState.accountMap
                        else
                          evmState.accountMap.insert r
                            {(default : Account) with balance := σ_Iₐ.balance}
                              |>.insert Iₐ {σ_Iₐ with balance := 0}
                      | some σ_r =>
                        if r ≠ Iₐ then
                          evmState.accountMap.insert r
                            {σ_r with balance := σ_r.balance + σ_Iₐ.balance}
                              |>.insert Iₐ {σ_Iₐ with balance := 0}
                        else
                          -- if the target is the same as the contract calling `SELFDESTRUCT` that Ether will be burnt.
                          evmState.accountMap.insert r {σ_r with balance := 0}
                            |>.insert Iₐ {σ_Iₐ with balance := 0}
              let evmState' :=
                {evmState with
                  accountMap := accountMap'
                  substate := A'
                }
              .ok <| evmState'.replaceStackAndIncrPC s
            else
              /- When SELFDESTRUCT is executed in a transaction that is not the
                same as the contract calling SELFDESTRUCT was created:
              -/
              let A' : Substate :=
                { evmState.substate with
                    accessedAccounts :=
                      evmState.substate.accessedAccounts.insert r
                }
              let accountMap' :=
                match evmState.lookupAccount Iₐ with
                  | none => dbg_trace "No 'self' found to be destructed; this should probably not be happening;"; evmState.accountMap
                  | some σ_Iₐ  =>
                    match evmState.lookupAccount r with
                      | none =>
                        if σ_Iₐ.balance == 0 then
                          evmState.accountMap
                        else
                          evmState.accountMap.insert r
                            {(default : Account) with balance := σ_Iₐ.balance}
                              |>.insert Iₐ {σ_Iₐ with balance := 0}
                      | some σ_r =>
                        if r ≠ Iₐ then
                          evmState.accountMap.insert r
                            {σ_r with balance := σ_r.balance + σ_Iₐ.balance}
                              |>.insert Iₐ {σ_Iₐ with balance := 0}
                        else
                          -- Note that if the target is the same as the contract
                          -- calling SELFDESTRUCT there is no net change in balances.
                          -- Unlike the prior specification, Ether will not be burnt in this case.
                          evmState.accountMap
              let evmState' :=
                {evmState with
                  accountMap := accountMap'
                  substate := A'
                }
              .ok <| evmState'.replaceStackAndIncrPC s
          | _ => .error .StackUnderflow
    | .INVALID => (λ _ ↦ .error .InvalidInstruction)
    | .Push .PUSH0 => λ evmState =>
        .ok <|
          evmState.replaceStackAndIncrPC (evmState.stack.push 0)
    | .Push _ => λ evmState => do
        let some (arg, argWidth) := arg | .error .StackUnderflow
        .ok <| evmState.replaceStackAndIncrPC (evmState.stack.push arg) (pcΔ := argWidth.succ)
    | .JUMP => λ evmState => do
        match evmState.stack.pop with
          | some ⟨stack , μ₀⟩ =>
            let newPc := μ₀
            .ok <| {evmState with pc := newPc, stack := stack}
          | _ => .error .StackUnderflow
    | .JUMPI => λ evmState => do
        match evmState.stack.pop2 with
          | some ⟨stack , μ₀, μ₁⟩ =>
            let newPc := if μ₁ != 0 then μ₀ else evmState.pc + 1
            .ok <| {evmState with pc := newPc, stack := stack}
          | _ => .error .StackUnderflow
    | .PC => λ evmState =>
        .ok <| evmState.replaceStackAndIncrPC (evmState.stack.push evmState.pc)
    | .JUMPDEST => λ evmState => do
        .ok <| evmState.incrPC
    | .DUP1 => dup 1
    | .DUP2 => dup 2
    | .DUP3 => dup 3
    | .DUP4 => dup 4
    | .DUP5 => dup 5
    | .DUP6 => dup 6
    | .DUP7 => dup 7
    | .DUP8 => dup 8
    | .DUP9 => dup 9
    | .DUP10 => dup 10
    | .DUP11 => dup 11
    | .DUP12 => dup 12
    | .DUP13 => dup 13
    | .DUP14 => dup 14
    | .DUP15 => dup 15
    | .DUP16 => dup 16
    | .SWAP1 => swap 1
    | .SWAP2 => swap 2
    | .SWAP3 => swap 3
    | .SWAP4 => swap 4
    | .SWAP5 => swap 5
    | .SWAP6 => swap 6
    | .SWAP7 => swap 7
    | .SWAP8 => swap 8
    | .SWAP9 => swap 9
    | .SWAP10 => swap 10
    | .SWAP11 => swap 11
    | .SWAP12 => swap 12
    | .SWAP13 => swap 13
    | .SWAP14 => swap 14
    | .SWAP15 => swap 15
    | .SWAP16 => swap 16
    | _ => λ _ ↦ default

